### ISSUE TITLE
Can the function also be exported as the "promisify" named function

### ISSUE THREAD

**Issue by vladimiry** [ljharb/util.promisify#11]
Not just as the default function. So we could import it as the named function. Yes I saw the shim thing, but that's the different story.

**Comment by ljharb** [comment]
It’s the default export; you can require or import it under any name you like. What would be the benefit of exporting it under a property?

**Comment by vladimiry** [comment]
The benefit is simple, I would be able import it as `import {promisify} from "util.promisify"` (or `const {promisify} = require("util.promisify")`) - the same way as I can import the original function with Node.js 8+ `import {promisify} from "util"`. Also I consider it as a good practice to name the same function in the same way across the entire app, with default imports people tend to name it in a very liberal way. Besides sometimes picking a right import name can be time consuming process :)

In my opinion it's in general a bad idea to use default exports at all. With named exports you can also name it in any way aliasing it with `as` keyword. After all if function does `promisify` action, why not name it respectively.

To be clear, I'm not asking to remove the default export, but simply in addition expose the same function as `promisify`.

**Comment by ljharb** [comment]
Because you can rename named imports, and destructured requires, named exports provide precisely zero additional consistency about naming. I agree that such consistency is useful, but it’s not within the ability, nor is it the place, of the exporting package to enforce. You can and should use a linter in your codebase if that’s something you want to ensure. 

This, it sounds like your only reason is so you can keep the { } - I’m not sure thats worth creating a circular reference and exposing additional API surface.

In general, most packages should only have a default export anyways - a default export is what a module *is*, and a named export is what a module *has*.

**Comment by vladimiry** [comment]
Another possible benefit is that with function named as `promisify` it would be easier to add Typescript declaration files, basically copy-pasting stuff from the Node's declarations. Right, the next feature request would be to add Typescript declaration files :)

**Comment by ljharb** [comment]
TypeScript files never belong in a non-TypeScript project; use DefinitelyTyped for that.

Separately, it’s identically as easy to add type defs to a default export as to a named one, as far as i understand it.

**Comment by vladimiry** [comment]
I currently have applied declarations like this https://github.com/vladimiry/fs-no-eperm-anymore/blob/c7360c22b770a44ed35cacd801a3deba0e01c54a/src/lib/private/promisify.ts and then import `promisify` like this https://github.com/vladimiry/fs-no-eperm-anymore/blob/c7360c22b770a44ed35cacd801a3deba0e01c54a/src/lib/private/constants.ts#L7 But that's certainly a hack.
