### ISSUE TITLE
Illegal invocation error thrown when trying to use promisified function

### ISSUE THREAD

**Issue by michael-ts** [ljharb/util.promisify#12]
```
const promisify = require("util.promisify")
var sqlite3 = require("cross-sqlcipher")
var db = new sqlite3.Database("testdb")
const exec = promisify(db.exec)
var promise = exec("PRAGMA KEY=\"ABCDEFG\"")
```

> (node:13872) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Illegal invocation

**Comment by ljharb** [comment]
`db.exec` seems like it's an instance method of `sqlite3.Database` - you may need to promisify `db.exec.bind(db)` so that it retains the proper `this` value.

**Comment by SOHELAHMED7** [comment]
Adding bit more info to above answer that might help beginners 

Line 

`const exec = promisify(db.exec)` 

is to be  changed to 

`const exec = promisify(db.exec.bind(db))`

**Comment by Fr33dan** [comment]
It took me a bit to understand what ljharb meant so I'm explaining it in a few more words for future confused people like me trying to apply this in different context.

Since `db.exec` is a function on the object `db` and thus can reference other properties and functions of `db` using the 'this' keyword. When that function is run by the `promisify` that method, it is no longer in the original context of the `db` object instance and thus can't find those functions. By using the `bind` function you create a copy of the function that will use the object you specify as `this` no matter the context. Thus by calling `bind` passing the original `db` object it was attached to the result will always use that `db` object as intended.
