### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): true

### ISSUE THREAD

**Issue by DavidGOrtega** [ljharb/util.promisify#13]
Node 7.7.4
Windows 10

functions that returns true are rejected?

```js
require('util.promisify/shim')();
const util = require('util');

const exists = util.promisify(fs.exists); 
async function test() {
    await exists("path_to_an_existing_file");
}
test();
```
```
(node:109376) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): true
```

**Comment by ljharb** [comment]
If it throws, then yes, it's rejected - even if if `throws true`.

In this case, however, the issue is that `fs.exists` doesn't have standard async behavior - its callback only ever gets called with one argument.

In node < 8, the solution is to do something like:
```js
fs.exists[util.promisify.custom] = path => new Promise(resolve => fs.exists(path, resolve));
```

However, this package currently does *not* contain all of the needed "custom" promisify shims that node 8+ does.

**Comment by DavidGOrtega** [comment]
@ljharb thanks for the reply.

Do you know any effort that tries to polyfill promisify like v8?

**Comment by ljharb** [comment]
I don’t know of any polyfill yet for all the custom implementations on core modules.
